from __future__ import annotations

from pathlib import Path
import json

OUTPUT_DIR = Path('checks')
OUTPUT_DIR.mkdir(exist_ok=True)

TEMPLATE = """<!DOCTYPE html>
<html lang=\"fr\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>{title_fr} · Consistency Checker</title>
    <link rel=\"stylesheet\" href=\"../assets/css/style.css\" />
  </head>
  <body data-page=\"detail\">
    <header class=\"primary-header\" role=\"banner\">
      <div class=\"header-content\">
        <a class=\"brand\" href=\"../index.html\">
          <span class=\"brand-title\">Centre MAESTRIA</span>
          <span class=\"brand-subtitle\">Consistency Checker</span>
        </a>
        <button\n          class=\"language-switch\"\n          type=\"button\"\n          role=\"switch\"\n          data-language-toggle\n          data-aria-label-to-en=\"Passer l'interface en anglais\"\n          data-aria-label-to-fr=\"Switch interface to French\"\n          aria-checked=\"false\"\n          data-active-lang=\"fr\"\n          aria-label=\"Passer l'interface en anglais\"\n          title=\"Passer l'interface en anglais\"\n        >
          <span class=\"language-switch-track\">
            <span class=\"language-switch-option language-switch-option--fr\">FR</span>
            <span class=\"language-switch-option language-switch-option--en\">EN</span>
            <span class=\"language-switch-thumb\" aria-hidden=\"true\"></span>
          </span>
        </button>
      </div>
    </header>
    <main>
      <h1 class=\"page-title\" data-fr=\"{title_fr}\" data-en=\"{title_en}\"></h1>
      <table class=\"info-table\">
        <tbody>
          <tr>
            <th data-fr=\"Identifiant\" data-en=\"Identifier\"></th>
            <td>{identifier}</td>
          </tr>
          <tr>
            <th data-fr=\"Niveau de criticité\" data-en=\"Criticality level\"></th>
            <td><span class=\"level-pill level-{level}\">{level}</span></td>
          </tr>
          <tr>
            <th data-fr=\"Statut en cas d'échec\" data-en=\"Status if failed\"></th>
            <td data-fr=\"{status_fr}\" data-en=\"{status_en}\">{status_fr}</td>
          </tr>
        </tbody>
      </table>
      <section class=\"content-section\">
        <h2 data-fr=\"Explications\" data-en=\"Overview\"></h2>
        <p data-fr=\"{overview_fr}\" data-en=\"{overview_en}\"></p>
      </section>
      <section class=\"content-section\">
        <h2 data-fr=\"Résolution\" data-en=\"Remediation\"></h2>
        <p data-fr=\"{remediation_fr}\" data-en=\"{remediation_en}\"></p>
      </section>
      <a class=\"return-button\" href=\"../index.html\" data-fr=\"Retour à la liste\" data-en=\"Back to list\"></a>
    </main>
    <footer class=\"primary-footer\">
      <div class=\"footer-brand\">MAESTRIA</div>
      <div class=\"footer-links\">
        <div class=\"footer-column\">
          <h3 data-fr=\"Support\" data-en=\"Support\"></h3>
          <ul>
            <li><span data-fr=\"Centre de services\" data-en=\"Service desk\"></span></li>
            <li><span data-fr=\"Documentation technique\" data-en=\"Technical documentation\"></span></li>
          </ul>
        </div>
        <div class=\"footer-column\">
          <h3 data-fr=\"Mentions\" data-en=\"Legal\"></h3>
          <ul>
            <li><span data-fr=\"Mentions légales\" data-en=\"Legal notice\"></span></li>
            <li><span data-fr=\"Politique de confidentialité\" data-en=\"Privacy policy\"></span></li>
          </ul>
        </div>
      </div>
    </footer>
    <script src=\"../assets/js/script.js\"></script>
  </body>
</html>
"""

STATUS_LABELS = {
    "FATAL_ERROR": {
        "fr": "Blocage critique (FATAL_ERROR)",
        "en": "Blocking failure (FATAL_ERROR)",
    },
    "ERROR": {
        "fr": "Échec majeur (ERROR)",
        "en": "Major failure (ERROR)",
    },
    "WARNING": {
        "fr": "Avertissement à résoudre (WARNING)",
        "en": "Warning to address (WARNING)",
    },
    "INFORMATION": {
        "fr": "Information (INFORMATION)",
        "en": "Information (INFORMATION)",
    },
}

CHECKS = [
    {
        "slug": "powershell_activated",
        "identifier": "CHK-FAT-001",
        "title_fr": "PowerShell activé",
        "title_en": "PowerShell activated",
        "level": "FATAL_ERROR",
        "overview_fr": "S'assure que PowerShell est disponible et que la stratégie d'exécution n'est pas définie sur Restreint.",
        "overview_en": "Ensures that PowerShell is available and that the execution policy is not set to Restricted.",
        "remediation_fr": "Activer PowerShell et ajuster la stratégie d'exécution (par exemple RemoteSigned) afin d'autoriser l'exécution des scripts requis.",
        "remediation_en": "Enable PowerShell and adjust the execution policy (for example RemoteSigned) so that required scripts can run.",
        "script": "N/A",
    },
    {
        "slug": "powershell_unrestricted",
        "identifier": "CHK-FAT-002",
        "title_fr": "PowerShell en mode non restreint",
        "title_en": "PowerShell unrestricted",
        "level": "FATAL_ERROR",
        "overview_fr": "Contrôle que la stratégie d'exécution PowerShell de la machine locale est définie sur Unrestricted et qu'aucune politique n'est en mode Restreint ou Indéfini.",
        "overview_en": "Checks that the local machine PowerShell execution policy is set to Unrestricted and that no policy remains Restricted or Undefined.",
        "remediation_fr": "Exécuter \"Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine\" puis vérifier toutes les portées pour éliminer les modes restreints.",
        "remediation_en": "Run \"Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine\" and review every scope to remove restricted policies.",
        "script": "N/A",
    },
    {
        "slug": "registry_writable",
        "identifier": "CHK-FAT-003",
        "title_fr": "Registre accessible en écriture",
        "title_en": "Registry is writable",
        "level": "FATAL_ERROR",
        "overview_fr": "Vérifie que le registre système peut être modifié par l'installateur.",
        "overview_en": "Verifies that the system registry can be modified by the installer.",
        "remediation_fr": "Débloquer les autorisations sur les clés de registre requises ou exécuter l'installation avec un compte ayant les droits suffisants.",
        "remediation_en": "Restore permissions on the required registry keys or run the setup with an account that has sufficient rights.",
        "script": "N/A",
    },
    {
        "slug": "postgresql_running",
        "identifier": "CHK-FAT-004",
        "title_fr": "Service PostgreSQL actif",
        "title_en": "PostGre SQL running",
        "level": "FATAL_ERROR",
        "overview_fr": "Confirme que le service bMx PostGre QLI Server est présent et démarré sur le système.",
        "overview_en": "Confirms that the bMx PostGre QLI Server service is installed and running on the system.",
        "remediation_fr": "Vérifier l'installation de PostgreSQL, démarrer le service et résoudre les erreurs éventuelles avant de relancer le contrôle.",
        "remediation_en": "Validate the PostgreSQL installation, start the service, and resolve any errors before rerunning the check.",
        "script": "N/A",
    },
    {
        "slug": "language_set_to_english",
        "identifier": "CHK-FAT-005",
        "title_fr": "Langue système en anglais",
        "title_en": "Language set to English",
        "level": "FATAL_ERROR",
        "overview_fr": "Vérifie que la langue de Windows est définie sur Anglais afin de garantir la compatibilité de l'application.",
        "overview_en": "Checks that the Windows language is set to English to guarantee application compatibility.",
        "remediation_fr": "Définir l'ensemble des paramètres régionaux Windows sur Anglais (États-Unis) puis redémarrer si nécessaire.",
        "remediation_en": "Set all Windows regional settings to English (United States) and reboot if required.",
        "script": "N/A",
    },
    {
        "slug": "cp_variables",
        "identifier": "CHK-FAT-006",
        "title_fr": "Variables Common Platform",
        "title_en": "CP Variables",
        "level": "FATAL_ERROR",
        "overview_fr": "Contrôle que les variables d'environnement Common Platform (programs, data, db, backup) pointent vers les emplacements recommandés.",
        "overview_en": "Checks that the Common Platform environment variables (programs, data, db, backup) target the recommended locations.",
        "remediation_fr": "Mettre à jour les variables d'environnement BIOMERIEUX_* pour qu'elles correspondent aux chemins D:/ et F:/ indiqués.",
        "remediation_en": "Update the BIOMERIEUX_* environment variables so that they match the recommended D:/ and F:/ paths.",
        "script": "N/A",
    },
    {
        "slug": "disks_unlocked",
        "identifier": "CHK-FAT-007",
        "title_fr": "Disques déverrouillés",
        "title_en": "Disks unlocked",
        "level": "FATAL_ERROR",
        "overview_fr": "S'assure qu'aucun volume requis par l'installation n'est verrouillé.",
        "overview_en": "Ensures that no volume required for the installation is locked.",
        "remediation_fr": "Déverrouiller tous les disques protégés et confirmer que les volumes nécessaires sont montés et accessibles.",
        "remediation_en": "Unlock any protected disks and confirm that the required volumes are mounted and accessible.",
        "script": "N/A",
    },
    {
        "slug": "current_account_admin_privilege",
        "identifier": "CHK-ERR-001",
        "title_fr": "Compte courant avec privilèges admin",
        "title_en": "Current account ADMIN privilege",
        "level": "ERROR",
        "overview_fr": "Vérifie que le compte utilisé dispose des privilèges administrateur.",
        "overview_en": "Ensures that the account in use has administrator privileges.",
        "remediation_fr": "Utiliser un compte membre du groupe Administrateurs locaux ou demander l'élévation adéquate.",
        "remediation_en": "Use an account that belongs to the local Administrators group or request the appropriate elevation.",
        "script": "N/A",
    },
    {
        "slug": "bci_link_not_enabled",
        "identifier": "CHK-ERR-002",
        "title_fr": "BCI Link désactivé",
        "title_en": "BCI Link not enabled",
        "level": "ERROR",
        "overview_fr": "S'assure que BCI Link n'est pas installé ou est désactivé.",
        "overview_en": "Ensures that BCI Link is not installed or is disabled.",
        "remediation_fr": "Désinstaller ou désactiver BCI Link avant de poursuivre la migration.",
        "remediation_en": "Uninstall or disable BCI Link before proceeding with the migration.",
        "script": "N/A",
    },
    {
        "slug": "hostname_validation",
        "identifier": "CHK-ERR-003",
        "title_fr": "Nom d'hôte conforme",
        "title_en": "hostname",
        "level": "ERROR",
        "overview_fr": "Contrôle que le nom d'hôte ne contient pas de soulignement et comporte moins de 16 caractères.",
        "overview_en": "Checks that the hostname does not contain underscores and is shorter than 16 characters.",
        "remediation_fr": "Renommer le serveur en respectant la longueur maximale et les caractères autorisés, puis redémarrer.",
        "remediation_en": "Rename the server using allowed characters within the length limit and reboot afterwards.",
        "script": "N/A",
    },
    {
        "slug": "no_global_updater_running",
        "identifier": "CHK-ERR-004",
        "title_fr": "Aucun Global Updater en cours",
        "title_en": "No Global Updater already running",
        "level": "ERROR",
        "overview_fr": "Vérifie qu'aucun processus Global Updater n'est actuellement actif.",
        "overview_en": "Ensures that no Global Updater process is currently running.",
        "remediation_fr": "Terminer ou planifier la fin du processus Global Updater avant d'initialiser la migration.",
        "remediation_en": "Stop or wait for the Global Updater process to finish before starting the migration.",
        "script": "N/A",
    },
    {
        "slug": "no_dbeaver_pgadmin_running",
        "identifier": "CHK-ERR-005",
        "title_fr": "Pas de DBeaver ni PGAdmin actifs",
        "title_en": "No running dbeaver nor PGAdmin",
        "level": "ERROR",
        "overview_fr": "Confirme que DBeaver et pgAdmin ne sont pas en cours d'exécution.",
        "overview_en": "Confirms that neither DBeaver nor pgAdmin is running.",
        "remediation_fr": "Fermer toutes les sessions clientes DBeaver ou pgAdmin avant de relancer le contrôle.",
        "remediation_en": "Close any DBeaver or pgAdmin client sessions before rerunning the check.",
        "script": "N/A",
    },
    {
        "slug": "windows_version_supported",
        "identifier": "CHK-ERR-006",
        "title_fr": "Version Windows supportée",
        "title_en": "Windows version",
        "level": "ERROR",
        "overview_fr": "Vérifie que le système d'exploitation est Windows 10, Server 2016, 2019 ou 2022.",
        "overview_en": "Checks that the operating system is Windows 10, Server 2016, 2019, or 2022.",
        "remediation_fr": "Mettre à niveau le système vers une version de Windows supportée avant la migration.",
        "remediation_en": "Upgrade the system to a supported Windows release before migration.",
        "script": "N/A",
    },
    {
        "slug": "no_pending_reboot",
        "identifier": "CHK-ERR-007",
        "title_fr": "Aucun redémarrage en attente",
        "title_en": "No pending reboot",
        "level": "ERROR",
        "overview_fr": "S'assure qu'aucun redémarrage Windows n'est requis (ex. suite à une mise à jour).",
        "overview_en": "Ensures that Windows does not require a reboot (for example after updates).",
        "remediation_fr": "Redémarrer le serveur pour appliquer les opérations en attente puis relancer le contrôle.",
        "remediation_en": "Restart the server to apply pending operations and rerun the check.",
        "script": "N/A",
    },
    {
        "slug": "free_disk_space",
        "identifier": "CHK-ERR-008",
        "title_fr": "Espace disque libre suffisant",
        "title_en": "Free disk space",
        "level": "ERROR",
        "overview_fr": "Vérifie que les lecteurs C:, D:, E: disposent d'au moins 5 Go et que F: possède 30 Go libres.",
        "overview_en": "Checks that drives C:, D:, E: have at least 5 GB free and drive F: has 30 GB available.",
        "remediation_fr": "Libérer ou étendre l'espace disque sur les volumes concernés avant la mise à jour.",
        "remediation_en": "Free or extend disk space on the affected volumes before the upgrade.",
        "script": "N/A",
    },
    {
        "slug": "cas_configuration",
        "identifier": "CHK-ERR-009",
        "title_fr": "Configuration CAS",
        "title_en": "CAS configuration",
        "level": "ERROR",
        "overview_fr": "Contrôle la cohérence des dossiers de configuration liés à CAS.",
        "overview_en": "Checks that the CAS configuration folders are consistent.",
        "remediation_fr": "Vérifier la présence et la structure attendue des dossiers CAS puis corriger les incohérences.",
        "remediation_en": "Verify that CAS folders exist with the expected structure and fix any inconsistencies.",
        "script": "N/A",
    },
    {
        "slug": "all_hypervisor",
        "identifier": "CHK-ERR-010",
        "title_fr": "Personnalisation All Hypervisor",
        "title_en": "All Hypervisor",
        "level": "ERROR",
        "overview_fr": "Vérifie que la personnalisation système All Hypervisor a été appliquée.",
        "overview_en": "Ensures that the All Hypervisor system customization has been applied.",
        "remediation_fr": "Appliquer les scripts de personnalisation All Hypervisor documentés avant la migration.",
        "remediation_en": "Apply the documented All Hypervisor customization scripts before migration.",
        "script": "N/A",
    },
    {
        "slug": "bact_instrument_id",
        "identifier": "CHK-ERR-011",
        "title_fr": "Identifiant BACT défini",
        "title_en": "BACT instrument ID",
        "level": "ERROR",
        "overview_fr": "Vérifie que l'identifiant d'instrument BACT existe et vaut 1.",
        "overview_en": "Checks that the BACT instrument ID exists and equals 1.",
        "remediation_fr": "Corriger la configuration BACT afin de définir l'identifiant sur 1.",
        "remediation_en": "Adjust the BACT configuration so that the identifier is set to 1.",
        "script": "N/A",
    },
    {
        "slug": "ipv4_enabled",
        "identifier": "CHK-ERR-012",
        "title_fr": "IPv4 activé",
        "title_en": "IPv4",
        "level": "ERROR",
        "overview_fr": "S'assure que le protocole IPv4 est activé sur les interfaces réseau.",
        "overview_en": "Ensures that IPv4 is enabled on the network interfaces.",
        "remediation_fr": "Activer IPv4 sur chaque carte réseau utilisée par la plateforme.",
        "remediation_en": "Enable IPv4 on every network adapter used by the platform.",
        "script": "N/A",
    },
    {
        "slug": "no_pending_messages",
        "identifier": "CHK-ERR-013",
        "title_fr": "Aucun message MYLA en attente",
        "title_en": "No pending messages",
        "level": "ERROR",
        "overview_fr": "Vérifie que la table jbmm.msg ne contient plus de messages en attente.",
        "overview_en": "Checks that the jbmm.msg table no longer contains pending messages.",
        "remediation_fr": "Traiter ou purger les messages en attente afin de repartir d'un état propre.",
        "remediation_en": "Process or purge the pending messages to start from a clean state.",
        "script": "N/A",
    },
    {
        "slug": "no_duplicates_modules_stations",
        "identifier": "CHK-ERR-014",
        "title_fr": "Pas de doublons de modules et stations",
        "title_en": "No duplicates",
        "level": "ERROR",
        "overview_fr": "S'assure qu'il n'existe pas de doublon de modules ou de stations dans MYLA.",
        "overview_en": "Ensures that modules and stations in MYLA are not duplicated.",
        "remediation_fr": "Identifier et supprimer les doublons dans la configuration MYLA avant de poursuivre.",
        "remediation_en": "Identify and remove duplicates in the MYLA configuration before proceeding.",
        "script": "N/A",
    },
    {
        "slug": "no_backup_in_progress",
        "identifier": "CHK-ERR-015",
        "title_fr": "Aucune sauvegarde en cours",
        "title_en": "No backup in progress",
        "level": "ERROR",
        "overview_fr": "Vérifie qu'aucune sauvegarde système n'est en exécution.",
        "overview_en": "Checks that no system backup is currently running.",
        "remediation_fr": "Attendre la fin de la sauvegarde ou la reprogrammer avant la migration.",
        "remediation_en": "Wait for the backup to finish or reschedule it before migration.",
        "script": "N/A",
    },
    {
        "slug": "uuid_check",
        "identifier": "CHK-ERR-016",
        "title_fr": "UUID cohérents",
        "title_en": "UUID check",
        "level": "ERROR",
        "overview_fr": "S'assure qu'aucun UUID n'est dupliqué ou vide.",
        "overview_en": "Ensures that there are no duplicate or null UUID values.",
        "remediation_fr": "Corriger les enregistrements concernés afin de garantir des UUID uniques et non nuls.",
        "remediation_en": "Fix the impacted records to guarantee unique, non-null UUIDs.",
        "script": "N/A",
    },
    {
        "slug": "no_duplicates_pseudo_drugs",
        "identifier": "CHK-ERR-017",
        "title_fr": "Pas de doublons de pseudo médicaments",
        "title_en": "No duplicates in pseudo drugs",
        "level": "ERROR",
        "overview_fr": "Vérifie qu'il n'existe pas de pseudo médicament dupliqué.",
        "overview_en": "Checks that no pseudo drug entries are duplicated.",
        "remediation_fr": "Supprimer ou fusionner les pseudo médicaments dupliqués dans la base.",
        "remediation_en": "Remove or merge the duplicated pseudo drug entries in the database.",
        "script": "N/A",
    },
    {
        "slug": "no_etl_in_progress",
        "identifier": "CHK-ERR-018",
        "title_fr": "Aucun ETL en cours",
        "title_en": "No ETL in progress",
        "level": "ERROR",
        "overview_fr": "Confirme qu'aucun processus ETL n'est actif.",
        "overview_en": "Confirms that no ETL process is running.",
        "remediation_fr": "Attendre la fin de l'ETL ou l'arrêter proprement avant la migration.",
        "remediation_en": "Wait for the ETL to finish or stop it gracefully before migration.",
        "script": "N/A",
    },
    {
        "slug": "no_active_lis_bci",
        "identifier": "CHK-ERR-019",
        "title_fr": "Aucun LIS actif pour BCI Link",
        "title_en": "No active LIS for BCI Link",
        "level": "ERROR",
        "overview_fr": "S'assure qu'aucun LIS n'utilise actuellement le BCI Link.",
        "overview_en": "Ensures that no LIS is currently using the BCI Link.",
        "remediation_fr": "Suspendre les échanges LIS via BCI Link avant de procéder à la migration.",
        "remediation_en": "Suspend LIS communication through BCI Link prior to migration.",
        "script": "N/A",
    },
    {
        "slug": "no_duplicates_topology",
        "identifier": "CHK-ERR-020",
        "title_fr": "Pas de doublons dans la topologie",
        "title_en": "No duplicates in topo",
        "level": "ERROR",
        "overview_fr": "Vérifie l'absence de doublons dans les tables topo.station et topo.module.",
        "overview_en": "Checks for duplicates in the topo.station and topo.module tables.",
        "remediation_fr": "Nettoyer les doublons détectés dans la topologie avant migration.",
        "remediation_en": "Clean up the detected duplicates in topology before migration.",
        "script": "N/A",
    },
    {
        "slug": "shared_folders_acl",
        "identifier": "CHK-ERR-021",
        "title_fr": "Partages réseau conformes",
        "title_en": "Shared folders",
        "level": "ERROR",
        "overview_fr": "Vérifie qu'aucun dossier partagé avec des ACL spécifiques n'est défini sur les répertoires critiques.",
        "overview_en": "Ensures that no shared folder with specific ACLs is configured on critical directories.",
        "remediation_fr": "Supprimer ou ajuster les partages détectés selon la politique recommandée.",
        "remediation_en": "Remove or adjust the detected shares to align with the recommended policy.",
        "script": "N/A",
    },
    {
        "slug": "sql_procedures_owned_by_postgre",
        "identifier": "CHK-ERR-022",
        "title_fr": "Procédures SQL propriété Postgre",
        "title_en": "SQL procedures",
        "level": "ERROR",
        "overview_fr": "S'assure qu'aucune procédure SQL du schéma public n'est détenue par l'utilisateur Postgre.",
        "overview_en": "Ensures that no SQL procedures in the public schema are owned by Postgre.",
        "remediation_fr": "Réattribuer les procédures concernées à l'utilisateur attendu.",
        "remediation_en": "Reassign the affected procedures to the expected owner.",
        "script": "N/A",
    },
    {
        "slug": "unsupported_characters_code_mapper",
        "identifier": "CHK-ERR-023",
        "title_fr": "Caractères supportés dans Code Mapper",
        "title_en": "Unsupported characters in Code mapper",
        "level": "ERROR",
        "overview_fr": "Contrôle l'absence d'espaces en début ou fin et de caractères interdits dans Code Mapper.",
        "overview_en": "Checks for leading/trailing spaces or forbidden characters in Code Mapper.",
        "remediation_fr": "Nettoyer les valeurs Code Mapper pour respecter les règles de nommage.",
        "remediation_en": "Clean up Code Mapper values to comply with naming rules.",
        "script": "N/A",
    },
    {
        "slug": "specimen_category_length",
        "identifier": "CHK-ERR-024",
        "title_fr": "Longueur des catégories de prélèvements",
        "title_en": "Specimen category length",
        "level": "ERROR",
        "overview_fr": "Vérifie que les codes de catégorie de prélèvement ne sont ni dupliqués ni supérieurs à 24 caractères.",
        "overview_en": "Checks that specimen category codes are unique and shorter than 24 characters.",
        "remediation_fr": "Ajuster les codes concernés pour respecter longueur et unicité.",
        "remediation_en": "Adjust the impacted codes to respect length and uniqueness requirements.",
        "script": "N/A",
    },
    {
        "slug": "minimal_physical_memory",
        "identifier": "CHK-ERR-025",
        "title_fr": "Mémoire physique minimale",
        "title_en": "Minimal physical memory",
        "level": "ERROR",
        "overview_fr": "Confirme que la mémoire physique installée est d'au moins 16 Go.",
        "overview_en": "Confirms that at least 16 GB of physical memory is installed.",
        "remediation_fr": "Ajouter de la mémoire ou libérer des ressources pour atteindre le minimum requis.",
        "remediation_en": "Add memory or free resources to meet the minimum requirement.",
        "script": "N/A",
    },
    {
        "slug": "ports_usage",
        "identifier": "CHK-ERR-026",
        "title_fr": "Ports conformes",
        "title_en": "Ports",
        "level": "ERROR",
        "overview_fr": "Contrôle que les ports requis sont utilisés par les bons processus ou disponibles.",
        "overview_en": "Checks that required ports are used by the expected processes or remain free.",
        "remediation_fr": "Réattribuer ou libérer les ports bloquants selon la matrice de communication.",
        "remediation_en": "Reassign or free blocking ports according to the communication matrix.",
        "script": "N/A",
    },
    {
        "slug": "database_locale",
        "identifier": "CHK-ERR-027",
        "title_fr": "Locale base de données",
        "title_en": "Database locale",
        "level": "ERROR",
        "overview_fr": "S'assure que la base de données est configurée en 'English United States'.",
        "overview_en": "Ensures that the database locale is 'English United States'.",
        "remediation_fr": "Adapter la configuration régionale de la base ou restaurer un backup conforme.",
        "remediation_en": "Adjust the database regional settings or restore a compliant backup.",
        "script": "N/A",
    },
    {
        "slug": "powershell_requirements",
        "identifier": "CHK-ERR-028",
        "title_fr": "Prérequis PowerShell",
        "title_en": "PowerShell requirements",
        "level": "ERROR",
        "overview_fr": "Vérifie que la version de PowerShell installée répond à la version minimale attendue (5.1).",
        "overview_en": "Checks that the installed PowerShell version meets the minimal requirement (5.1).",
        "remediation_fr": "Mettre à jour PowerShell vers la version 5.1 ou supérieure.",
        "remediation_en": "Update PowerShell to version 5.1 or later.",
        "script": "N/A",
    },
    {
        "slug": "common_platform_variables_alignment",
        "identifier": "CHK-ERR-029",
        "title_fr": "Variables Common Platform cohérentes",
        "title_en": "Common Platform variables",
        "level": "ERROR",
        "overview_fr": "Vérifie la correspondance des variables Common Platform pour MAESTRIA et MYLA.",
        "overview_en": "Ensures Common Platform variables align with MAESTRIA and MYLA expectations.",
        "remediation_fr": "Mettre en conformité les variables d'environnement selon les guides produits.",
        "remediation_en": "Align the environment variables with the product guidelines.",
        "script": "N/A",
    },
    {
        "slug": "session_timeout",
        "identifier": "CHK-ERR-030",
        "title_fr": "Délai d'expiration de session",
        "title_en": "Session timeout",
        "level": "ERROR",
        "overview_fr": "S'assure que le délai d'expiration de session est au moins de 4 heures.",
        "overview_en": "Ensures that the session timeout is at least 4 hours.",
        "remediation_fr": "Allonger le délai de session conformément aux préconisations.",
        "remediation_en": "Extend the session timeout according to the recommendations.",
        "script": "N/A",
    },
    {
        "slug": "vitek_ms_not_installed",
        "identifier": "CHK-ERR-031",
        "title_fr": "Vitek MS 3.0 non installé",
        "title_en": "Vitek MS 3.0 not installed",
        "level": "ERROR",
        "overview_fr": "S'assure que Vitek MS 3.0 n'est pas installé ou est désactivé.",
        "overview_en": "Ensures that Vitek MS 3.0 is not installed or is disabled.",
        "remediation_fr": "Désinstaller ou désactiver Vitek MS 3.0 avant migration.",
        "remediation_en": "Uninstall or disable Vitek MS 3.0 before migration.",
        "script": "N/A",
    },
    {
        "slug": "biofire_not_installed",
        "identifier": "CHK-ERR-032",
        "title_fr": "BioFire non installé",
        "title_en": "BioFire not installed",
        "level": "ERROR",
        "overview_fr": "Vérifie que le pilote MAESTRIA@BioFire n'est pas présent avant migration.",
        "overview_en": "Checks that the MAESTRIA@BioFire driver is not installed before migration.",
        "remediation_fr": "Sauvegarder la configuration puis désinstaller le pilote BioFire.",
        "remediation_en": "Back up the configuration and uninstall the BioFire driver.",
        "script": "N/A",
    },
    {
        "slug": "sirweb_not_installed",
        "identifier": "CHK-ERR-033",
        "title_fr": "SirWeb non installé",
        "title_en": "SirWeb not installed",
        "level": "ERROR",
        "overview_fr": "S'assure que le pilote MAESTRIA@Sirweb n'est pas installé avant migration.",
        "overview_en": "Ensures that the MAESTRIA@Sirweb driver is not installed before migration.",
        "remediation_fr": "Désinstaller le pilote SirWeb avant de poursuivre.",
        "remediation_en": "Uninstall the SirWeb driver before proceeding.",
        "script": "N/A",
    },
    {
        "slug": "lis_driver_installed",
        "identifier": "CHK-ERR-034",
        "title_fr": "Pilote LIS installé",
        "title_en": "LIS driver installed",
        "level": "ERROR",
        "overview_fr": "Vérifie que le pilote MYLA@LIS est installé avant migration.",
        "overview_en": "Verifies that the MYLA@LIS driver is installed before migration.",
        "remediation_fr": "Installer le pilote LIS requis avant de continuer.",
        "remediation_en": "Install the required LIS driver before continuing.",
        "script": "N/A",
    },
    {
        "slug": "reveal_not_installed",
        "identifier": "CHK-ERR-035",
        "title_fr": "Reveal non installé",
        "title_en": "Reveal not installed",
        "level": "ERROR",
        "overview_fr": "S'assure que le pilote MYLA@Reveal n'est pas installé avant migration.",
        "overview_en": "Ensures that the MYLA@Reveal driver is not installed before migration.",
        "remediation_fr": "Retirer le pilote Reveal avant l'opération.",
        "remediation_en": "Remove the Reveal driver before the operation.",
        "script": "N/A",
    },
    {
        "slug": "old_vitek_ms_driver",
        "identifier": "CHK-ERR-036",
        "title_fr": "Ancien pilote Vitek MS",
        "title_en": "Old Vitek MS driver",
        "level": "ERROR",
        "overview_fr": "Vérifie que le pilote MYLA@VitekMS 1.0.0.0 n'est pas installé.",
        "overview_en": "Ensures that the MYLA@VitekMS 1.0.0.0 driver is not installed.",
        "remediation_fr": "Désinstaller l'ancien pilote et planifier l'installation de la version supportée.",
        "remediation_en": "Uninstall the old driver and plan the installation of the supported version.",
        "script": "N/A",
    },
    {
        "slug": "adagio_name",
        "identifier": "CHK-ERR-037",
        "title_fr": "Nom Adagio conforme",
        "title_en": "Adagio name",
        "level": "ERROR",
        "overview_fr": "S'assure que le nom de l'instrument Adagio n'excède pas 14 caractères et ne contient pas de soulignement.",
        "overview_en": "Ensures that the Adagio instrument name is at most 14 characters and has no underscore.",
        "remediation_fr": "Renommer l'instrument Adagio selon les contraintes.",
        "remediation_en": "Rename the Adagio instrument to follow the constraints.",
        "script": "N/A",
    },
    {
        "slug": "biomic_name",
        "identifier": "CHK-ERR-038",
        "title_fr": "Nom Biomic conforme",
        "title_en": "Biomic name",
        "level": "ERROR",
        "overview_fr": "Vérifie que le nom de l'instrument BIOMIC ne dépasse pas 14 caractères.",
        "overview_en": "Checks that the BIOMIC instrument name is not longer than 14 characters.",
        "remediation_fr": "Renommer l'instrument BIOMIC pour respecter la longueur.",
        "remediation_en": "Rename the BIOMIC instrument to respect the length.",
        "script": "N/A",
    },
    {
        "slug": "bact_name",
        "identifier": "CHK-ERR-039",
        "title_fr": "Nom BacT conforme",
        "title_en": "BacT name",
        "level": "ERROR",
        "overview_fr": "Vérifie que le nom BacT ne contient que des caractères autorisés et aucun espace final.",
        "overview_en": "Ensures that the BacT name only uses allowed characters and no trailing space.",
        "remediation_fr": "Renommer les instruments BacT selon les règles de nommage.",
        "remediation_en": "Rename BacT instruments according to the naming rules.",
        "script": "N/A",
    },
    {
        "slug": "no_bact_duplicate",
        "identifier": "CHK-ERR-040",
        "title_fr": "Pas de doublons BacT",
        "title_en": "No BacT duplicate",
        "level": "ERROR",
        "overview_fr": "S'assure que les noms BacT ne sont pas dupliqués dans BTA.",
        "overview_en": "Ensures that BacT names are not duplicated in BTA.",
        "remediation_fr": "Supprimer les doublons BacT dans la configuration.",
        "remediation_en": "Remove BacT duplicates from the configuration.",
        "script": "N/A",
    },
    {
        "slug": "no_anonymization_tablespace",
        "identifier": "CHK-ERR-041",
        "title_fr": "Pas de tablespace d'anonymisation",
        "title_en": "No anonymization tablespace",
        "level": "ERROR",
        "overview_fr": "Vérifie qu'aucun tablespace d'anonymisation n'est présent dans la base.",
        "overview_en": "Ensures that no anonymization tablespace exists in the database.",
        "remediation_fr": "Supprimer le tablespace d'anonymisation détecté.",
        "remediation_en": "Remove the detected anonymization tablespace.",
        "script": "N/A",
    },
    {
        "slug": "no_lis_duplicate",
        "identifier": "CHK-ERR-042",
        "title_fr": "Pas de doublons LIS",
        "title_en": "No LIS duplicate",
        "level": "ERROR",
        "overview_fr": "S'assure qu'aucun identifiant de système LIS n'est dupliqué.",
        "overview_en": "Ensures that LIS system identifiers are not duplicated.",
        "remediation_fr": "Corriger les doublons d'identifiants LIS avant migration.",
        "remediation_en": "Fix duplicate LIS identifiers before migration.",
        "script": "N/A",
    },
    {
        "slug": "vc_result",
        "identifier": "CHK-ERR-043",
        "title_fr": "Résultat VC cohérent",
        "title_en": "VC Result",
        "level": "ERROR",
        "overview_fr": "Vérifie la cohérence du résultat VC 100.613.03.01.",
        "overview_en": "Ensures that VC result ID 100.613.03.01 is consistent.",
        "remediation_fr": "Réconcilier les données VC selon la procédure de support.",
        "remediation_en": "Reconcile the VC data following the support procedure.",
        "script": "N/A",
    },
    {
        "slug": "check_bmx_admin",
        "identifier": "CHK-ERR-044",
        "title_fr": "Compte bmx_admin conforme",
        "title_en": "Check bmx_admin",
        "level": "ERROR",
        "overview_fr": "S'assure que le compte en cours n'appartient pas au groupe bMxServices.",
        "overview_en": "Ensures that the current account does not belong to the bMxServices group.",
        "remediation_fr": "Utiliser un compte hors du groupe bMxServices pour la migration.",
        "remediation_en": "Use an account outside the bMxServices group for the migration.",
        "script": "N/A",
    },
    {
        "slug": "check_lab_analytics_sso",
        "identifier": "CHK-ERR-045",
        "title_fr": "Service Lab Analytics SSO arrêté",
        "title_en": "Check Lab Analytics SSO",
        "level": "ERROR",
        "overview_fr": "Signale la présence du service Lab Analytics SSO encore actif.",
        "overview_en": "Flags the Lab Analytics SSO service if it is still running.",
        "remediation_fr": "Arrêter le service Lab Analytics SSO avant migration.",
        "remediation_en": "Stop the Lab Analytics SSO service before migration.",
        "script": "N/A",
    },
    {
        "slug": "check_fips_activation",
        "identifier": "CHK-ERR-046",
        "title_fr": "Activation FIPS",
        "title_en": "Check FIPS activation",
        "level": "ERROR",
        "overview_fr": "Vérifie que FIPS est activé côté système et côté chocolately si requis.",
        "overview_en": "Checks that FIPS is enabled both on the system and within chocolately when required.",
        "remediation_fr": "Aligner la configuration FIPS entre Windows et chocolately puis relancer le contrôle.",
        "remediation_en": "Align the FIPS configuration between Windows and chocolately before rerunning the check.",
        "script": "N/A",
    },
    {
        "slug": "vitek2_duplicates",
        "identifier": "CHK-ERR-047",
        "title_fr": "Doublons Vitek 2",
        "title_en": "Vitek2 duplicates",
        "level": "ERROR",
        "overview_fr": "Détecte les identifiants d'instrument Vitek 2 en double pouvant bloquer la migration.",
        "overview_en": "Detects duplicate Vitek 2 instrument identifiers that may block migration.",
        "remediation_fr": "Contacter le support GCS pour résoudre les doublons Vitek 2.",
        "remediation_en": "Contact GCS support to resolve Vitek 2 duplicates.",
        "script": "N/A",
    },
    {
        "slug": "inconsistent_registry_value",
        "identifier": "CHK-ERR-048",
        "title_fr": "Valeurs de registre cohérentes",
        "title_en": "Inconsistent registry value",
        "level": "ERROR",
        "overview_fr": "Signale des clés de registre ne reflétant pas la version système réelle.",
        "overview_en": "Detects registry keys that do not reflect the actual system version.",
        "remediation_fr": "Corriger les clés de registre ou réappliquer l'installation partielle.",
        "remediation_en": "Correct the registry keys or reapply the partial installation steps.",
        "script": "N/A",
    },
    {
        "slug": "acl_failure_lab_analytics_sso",
        "identifier": "CHK-ERR-049",
        "title_fr": "ACL Lab Analytics SSO",
        "title_en": "ACL Failure - Lab Analytics SSO",
        "level": "ERROR",
        "overview_fr": "Détecte des fichiers ACL non conformes (MD5) sur plateformes Lab Analytics 5.0 en mode FIPS.",
        "overview_en": "Detects non-compliant ACL files (MD5) on Lab Analytics 5.0 platforms in FIPS mode.",
        "remediation_fr": "Mettre à jour les ACL selon les recommandations MAESTRIA 5.1.x.",
        "remediation_en": "Update the ACL files according to MAESTRIA 5.1.x recommendations.",
        "script": "N/A",
    },
    {
        "slug": "biotyper_driver_installed",
        "identifier": "CHK-ERR-050",
        "title_fr": "Pilote Biotyper installé",
        "title_en": "Biotyper driver is installed",
        "level": "ERROR",
        "overview_fr": "Vérifie si le pilote Biotyper est présent et susceptible de perturber la migration.",
        "overview_en": "Checks whether the Biotyper driver is installed and may cause migration issues.",
        "remediation_fr": "Sauvegarder la configuration puis désinstaller le pilote Biotyper.",
        "remediation_en": "Back up the configuration and uninstall the Biotyper driver.",
        "script": "N/A",
    },
    {
        "slug": "missing_hardware_registry_key",
        "identifier": "CHK-ERR-051",
        "title_fr": "Clé de registre matériel présente",
        "title_en": "Missing hardware registry key",
        "level": "ERROR",
        "overview_fr": "Vérifie l'existence de la clé HKEY_LOCAL_MACHINE\\SOFTWARE\\BioMerieux\\Hardware.",
        "overview_en": "Ensures that the HKEY_LOCAL_MACHINE\\SOFTWARE\\BioMerieux\\Hardware key exists.",
        "remediation_fr": "Créer ou restaurer la clé de registre manquante selon la documentation.",
        "remediation_en": "Create or restore the missing registry key following the documentation.",
        "script": "N/A",
    },
    {
        "slug": "tablespace_mismatch_postgresql",
        "identifier": "CHK-ERR-052",
        "title_fr": "Tablespaces PostgreSQL cohérents",
        "title_en": "Tablespace mismatch (PostgreSQL)",
        "level": "ERROR",
        "overview_fr": "Détecte une incohérence entre les tablespaces PostgreSQL et les disques physiques.",
        "overview_en": "Detects mismatches between PostgreSQL tablespaces and physical disks.",
        "remediation_fr": "Aligner l'affectation des tablespaces aux disques correspondants avant migration.",
        "remediation_en": "Align the tablespace assignments with the appropriate disks before migration.",
        "script": "N/A",
    },
    {
        "slug": "multi_lis_not_supported",
        "identifier": "CHK-WAR-001",
        "title_fr": "Multi-LIS non supporté",
        "title_en": "Multi-LIS not supported",
        "level": "WARNING",
        "overview_fr": "Informe qu'une configuration multi-LIS partageant le même SpecimenID a été détectée.",
        "overview_en": "Reports a multi-LIS configuration sharing the same SpecimenID.",
        "remediation_fr": "Adapter la configuration LIS afin d'éviter le partage de SpecimenID avant la mise à jour.",
        "remediation_en": "Adjust the LIS configuration to avoid shared SpecimenIDs before the upgrade.",
        "script": "N/A",
    },
    {
        "slug": "duplicate_entries_workflow",
        "identifier": "CHK-WAR-002",
        "title_fr": "Doublons workflow/executedrequest",
        "title_en": "Duplicate entries in workflow/executedrequest",
        "level": "WARNING",
        "overview_fr": "Signale des doublons pouvant provoquer l'exception TooManyResultsException.",
        "overview_en": "Highlights duplicates that can trigger a TooManyResultsException.",
        "remediation_fr": "Exécuter l'outil de déduplication pour nettoyer les enregistrements.",
        "remediation_en": "Run the deduplication tool to clean the records.",
        "script": "N/A",
    },
    {
        "slug": "no_common_platform_installed",
        "identifier": "CHK-WAR-003",
        "title_fr": "Aucun Common Platform installé",
        "title_en": "No CP installed",
        "level": "WARNING",
        "overview_fr": "Vérifie qu'aucune Common Platform n'est installée.",
        "overview_en": "Verifies that no Common Platform is installed.",
        "remediation_fr": "Installer la Common Platform si nécessaire selon le périmètre projet.",
        "remediation_en": "Install the Common Platform if required for the project scope.",
        "script": "N/A",
    },
    {
        "slug": "etl_success_last_month",
        "identifier": "CHK-WAR-004",
        "title_fr": "Succès ETL dernier mois",
        "title_en": "ETL success last month",
        "level": "WARNING",
        "overview_fr": "Informe si le processus ETL a réussi au cours du mois précédent.",
        "overview_en": "Reports whether the ETL process succeeded within the last month.",
        "remediation_fr": "Analyser les journaux ETL et résoudre les erreurs avant migration.",
        "remediation_en": "Review ETL logs and fix errors before migration.",
        "script": "N/A",
    },
    {
        "slug": "physical_memory_recommended",
        "identifier": "CHK-INF-001",
        "title_fr": "Mémoire physique recommandée",
        "title_en": "Physical memory",
        "level": "INFORMATION",
        "overview_fr": "Informe sur la présence des 24 Go de mémoire recommandés.",
        "overview_en": "Indicates whether the recommended 24 GB of memory is installed.",
        "remediation_fr": "Planifier une montée en mémoire si nécessaire pour atteindre la recommandation.",
        "remediation_en": "Plan a memory upgrade if needed to reach the recommendation.",
        "script": "N/A",
    },
    {
        "slug": "ipv6_disabled",
        "identifier": "CHK-INF-002",
        "title_fr": "IPv6 désactivé",
        "title_en": "IPv6 disabled",
        "level": "INFORMATION",
        "overview_fr": "Informe sur la désactivation d'IPv6 au niveau système ou carte réseau.",
        "overview_en": "Reports whether IPv6 is disabled at system or adapter level.",
        "remediation_fr": "Désactiver IPv6 si la politique réseau l'exige.",
        "remediation_en": "Disable IPv6 if required by network policy.",
        "script": "N/A",
    },
    {
        "slug": "no_antivirus_installed_info",
        "identifier": "CHK-INF-003",
        "title_fr": "Antivirus absent",
        "title_en": "No antivirus installed",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'absence d'antivirus installé sur la plateforme.",
        "overview_en": "Indicates that no antivirus solution is installed on the platform.",
        "remediation_fr": "Installer un antivirus supporté si nécessaire.",
        "remediation_en": "Install a supported antivirus solution if required.",
        "script": "N/A",
    },
    {
        "slug": "certificate_requirements",
        "identifier": "CHK-INF-004",
        "title_fr": "Exigences certificats",
        "title_en": "Certificate requirements",
        "level": "INFORMATION",
        "overview_fr": "Vérifie la conformité des noms alternatifs de certificat avec la Common Platform.",
        "overview_en": "Checks that certificate alternative names comply with Common Platform requirements.",
        "remediation_fr": "Adapter le certificat émis pour inclure les SAN requis.",
        "remediation_en": "Adjust the issued certificate to include required SAN entries.",
        "script": "N/A",
    },
    {
        "slug": "dns_names_virtuo_vitek2",
        "identifier": "CHK-INF-005",
        "title_fr": "DNS Virtuo et Vitek2",
        "title_en": "DNS names for Virtuo and Vitek2",
        "level": "INFORMATION",
        "overview_fr": "Vérifie la correspondance entre les endpoints BCI Connect et les noms DNS configurés.",
        "overview_en": "Checks that BCI Connect endpoints match the configured DNS names.",
        "remediation_fr": "Mettre à jour les DNS ou la configuration des endpoints pour les aligner.",
        "remediation_en": "Update DNS or endpoint configuration to align them.",
        "script": "N/A",
    },
    {
        "slug": "supported_platform",
        "identifier": "CHK-INF-006",
        "title_fr": "Plateforme supportée",
        "title_en": "Supported platform",
        "level": "INFORMATION",
        "overview_fr": "Informe si la plateforme identifiée fait partie des plateformes supportées.",
        "overview_en": "Indicates whether the detected platform is supported.",
        "remediation_fr": "Évaluer un changement de plateforme si nécessaire.",
        "remediation_en": "Consider switching platforms if required.",
        "script": "N/A",
    },
    {
        "slug": "non_compliant_mappings",
        "identifier": "CHK-INF-007",
        "title_fr": "Mappings non conformes",
        "title_en": "Non-compliant mappings",
        "level": "INFORMATION",
        "overview_fr": "Informe que certains mappings non conformes ont été exclus lors de l'import.",
        "overview_en": "Indicates that non-compliant mappings were discarded during import.",
        "remediation_fr": "Corriger les mappings rejetés avant un nouvel import.",
        "remediation_en": "Correct the discarded mappings before re-importing.",
        "script": "N/A",
    },
    {
        "slug": "patient_conflicts_not_resolved",
        "identifier": "CHK-INF-008",
        "title_fr": "Conflits patients non résolus",
        "title_en": "Patient conflicts not resolved",
        "level": "INFORMATION",
        "overview_fr": "Informe de la présence de conflits patients dupliqués qui ne sont pas encore résolus.",
        "overview_en": "Reports duplicate patient conflicts that remain unresolved.",
        "remediation_fr": "Finaliser la résolution des conflits patients concernés.",
        "remediation_en": "Finish resolving the relevant patient conflicts.",
        "script": "N/A",
    },
    {
        "slug": "dotnet_version",
        "identifier": "CHK-INF-009",
        "title_fr": "Version .NET",
        "title_en": ".Net version",
        "level": "INFORMATION",
        "overview_fr": "Informe sur la disponibilité de .NET 4.8 ou supérieur.",
        "overview_en": "Indicates whether .NET version 4.8 or later is available.",
        "remediation_fr": "Mettre à niveau le framework .NET si nécessaire.",
        "remediation_en": "Upgrade the .NET framework if required.",
        "script": "N/A",
    },
    {
        "slug": "dwh_initialization",
        "identifier": "CHK-INF-010",
        "title_fr": "Initialisation DWH",
        "title_en": "DWH initialization",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'état d'initialisation de l'entrepôt de données.",
        "overview_en": "Reports the initialization status of the data warehouse.",
        "remediation_fr": "Initialiser le DWH si ce n'est pas déjà fait.",
        "remediation_en": "Initialize the DWH if it has not been done yet.",
        "script": "N/A",
    },
    {
        "slug": "firewall_notifications",
        "identifier": "CHK-INF-011",
        "title_fr": "Notifications pare-feu",
        "title_en": "Firewall notifications",
        "level": "INFORMATION",
        "overview_fr": "Informe si les notifications du pare-feu sont autorisées.",
        "overview_en": "Indicates whether firewall notifications are allowed.",
        "remediation_fr": "Adapter la configuration selon la politique de sécurité.",
        "remediation_en": "Adjust the configuration according to security policy.",
        "script": "N/A",
    },
    {
        "slug": "last_fsb",
        "identifier": "CHK-INF-012",
        "title_fr": "Dernière sauvegarde système",
        "title_en": "Last FSB",
        "level": "INFORMATION",
        "overview_fr": "Informe sur la disponibilité d'une sauvegarde complète de moins d'un jour dans F:/RSBR_V1_backups.",
        "overview_en": "Indicates whether a full system backup less than a day old exists in F:/RSBR_V1_backups.",
        "remediation_fr": "Réaliser une sauvegarde complète si nécessaire.",
        "remediation_en": "Perform a full backup if required.",
        "script": "N/A",
    },
    {
        "slug": "bi_initialization",
        "identifier": "CHK-INF-013",
        "title_fr": "Initialisation BI",
        "title_en": "BI initialization",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'état d'initialisation de la BI MAESTRIA.",
        "overview_en": "Indicates the initialization status of MAESTRIA BI.",
        "remediation_fr": "Finaliser l'initialisation BI si nécessaire.",
        "remediation_en": "Complete BI initialization if required.",
        "script": "N/A",
    },
    {
        "slug": "latest_vitek_ms_driver",
        "identifier": "CHK-INF-014",
        "title_fr": "Dernier pilote Vitek MS",
        "title_en": "Latest Vitek MS driver installed",
        "level": "INFORMATION",
        "overview_fr": "Informe de la présence du pilote MYLA@VitekMS 2.0.1.1 sur les serveurs VITEK MS.",
        "overview_en": "Indicates whether the MYLA@VitekMS 2.0.1.1 driver is installed on VITEK MS servers.",
        "remediation_fr": "Mettre à jour le pilote Vitek MS si nécessaire.",
        "remediation_en": "Update the Vitek MS driver if required.",
        "script": "N/A",
    },
    {
        "slug": "no_bact_duplicates_info",
        "identifier": "CHK-INF-015",
        "title_fr": "Pas de doublons BacT actifs",
        "title_en": "No BacT duplicates",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'absence de doublons d'instruments BC actifs dans la topologie.",
        "overview_en": "Indicates that no active BC instrument names are duplicated in topology.",
        "remediation_fr": "Corriger les doublons détectés si nécessaire.",
        "remediation_en": "Fix any detected duplicates if necessary.",
        "script": "N/A",
    },
    {
        "slug": "no_data_management_lis",
        "identifier": "CHK-INF-016",
        "title_fr": "Aucun LIS data management",
        "title_en": "No data management LIS",
        "level": "INFORMATION",
        "overview_fr": "Informe s'il existe un LIS défini comme Data Management dans MYLA.",
        "overview_en": "Indicates whether any LIS is defined as Data Management in MYLA.",
        "remediation_fr": "Adapter la configuration LIS si nécessaire.",
        "remediation_en": "Adjust the LIS configuration if required.",
        "script": "N/A",
    },
    {
        "slug": "isolates_linked_to_bottles",
        "identifier": "CHK-INF-017",
        "title_fr": "Isolats liés aux flacons",
        "title_en": "Isolates linked to bottles",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'existence de liens isolats/flacons restant à résoudre.",
        "overview_en": "Reports any pending isolate-to-bottle links that need resolution.",
        "remediation_fr": "Finaliser l'association des isolats aux flacons concernés.",
        "remediation_en": "Complete the isolate-to-bottle associations as needed.",
        "script": "N/A",
    },
    {
        "slug": "patient_conflicts_not_resolved_again",
        "identifier": "CHK-INF-018",
        "title_fr": "Conflits patients non re-résolus",
        "title_en": "Patient conflicts not re-solved",
        "level": "INFORMATION",
        "overview_fr": "Informe des conflits patients requalifiés qui pourraient réapparaître après migration.",
        "overview_en": "Highlights requalified patient conflicts that may reappear after migration.",
        "remediation_fr": "Vérifier ces conflits et appliquer les corrections nécessaires.",
        "remediation_en": "Review these conflicts and apply required corrections.",
        "script": "N/A",
    },
    {
        "slug": "no_duplicate_specimen_categories",
        "identifier": "CHK-INF-019",
        "title_fr": "Pas de doublons de catégories de prélèvements",
        "title_en": "No duplicate specimen categories",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'unicité des codes de catégories de prélèvements utilisateur.",
        "overview_en": "Indicates whether user specimen category codes remain unique.",
        "remediation_fr": "Mettre à jour les codes si des doublons apparaissent.",
        "remediation_en": "Update codes if duplicates appear.",
        "script": "N/A",
    },
    {
        "slug": "windows_license",
        "identifier": "CHK-INF-020",
        "title_fr": "Licence Windows",
        "title_en": "Windows license",
        "level": "INFORMATION",
        "overview_fr": "Informe sur l'état d'activation de la licence Windows.",
        "overview_en": "Indicates the activation state of the Windows license.",
        "remediation_fr": "Activer Windows si la licence n'est pas valide.",
        "remediation_en": "Activate Windows if the license is not valid.",
        "script": "N/A",
    },
    {
        "slug": "windows_updates",
        "identifier": "CHK-INF-021",
        "title_fr": "Mises à jour Windows",
        "title_en": "Windows updates",
        "level": "INFORMATION",
        "overview_fr": "Informe sur la date de la dernière mise à jour Windows (moins de 60 jours).",
        "overview_en": "Indicates whether the last Windows update is less than 60 days old.",
        "remediation_fr": "Planifier les mises à jour Windows si nécessaire.",
        "remediation_en": "Plan Windows updates if required.",
        "script": "N/A",
    },
]

if not CHECKS:
    raise SystemExit("No checks defined")

manifest_entries = []

for index, check in enumerate(CHECKS, start=1):
    slug = check['slug']
    path = OUTPUT_DIR / f"{slug}.html"
    level = check["level"]
    status = STATUS_LABELS.get(level, {"fr": level, "en": level})
    payload = {
        **check,
        "status_fr": check.get("status_fr", status["fr"]),
        "status_en": check.get("status_en", status["en"]),
    }
    html = TEMPLATE.format(**payload)
    path.write_text(html, encoding='utf-8')

    manifest_entries.append(
        {
            "id": check["identifier"],
            "script": check.get("script", "N/A"),
            "level": check["level"],
            "title_fr": check["title_fr"],
            "title_en": check["title_en"],
            "description_fr": check["overview_fr"],
            "description_en": check["overview_en"],
            "file": f"checks/{slug}.html",
        }
    )

manifest_path = Path('manifest.json')
manifest_path.write_text(
    json.dumps(manifest_entries, indent=2, ensure_ascii=False) + "\n", encoding='utf-8'
)
